GC_URL = "i.bx.ihotel.cn"
TICKET_URL = "ticket.bx.ihotel.cn"
ORGCODE = "HMSD"
USER_CODE ="QDH_ADMIN"
PASSWORD ="CG6NnQsx79lyXQewDEG+y0KFUuLi95h+eVX6HYTVXjnZW/T52MuiEB+faDqt/I2LBxu+JV2MREYpJPv0GtOfnhcTXjU6X3gRUByqu+mNACRGxOFprSqWHbor72hXmut8ofactB8qGP+EILZ6QRcQTu6EyufJJ5ow/y+DOE4HLkca/IBwwCPAVvCQXV5BQX5ScsvPXCP7hp2zZSRbDciYpciEOoIs5317dRTypsdYCWVBfP0NoWkuReNx/lXc7bb1BQSasXpWPgtnO5Ugw1Wt+0N+Cwa6KB09GgyZY1pmoqNJiaX2LDZRNdmeEREgZKKH2JzBflO48g5ju9PJXS9QPQ=="